export * from './Home'
export * from './Platform'
export * from './Tour'
export * from './Financing'
export * from './Estates'
export * from './Institutions'
export * from './NotFound'
export * from './Demo'
