/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TourRouteImport } from './routes/tour'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as InstitutionsRouteImport } from './routes/institutions'
import { Route as FinancingRouteImport } from './routes/financing'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as EstatesRouteImport } from './routes/estates'
import { Route as IndexRouteImport } from './routes/index'

const TourRoute = TourRouteImport.update({
    id: '/tour',
    path: '/tour',
    getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
    id: '/pricing',
    path: '/pricing',
    getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
    id: '/platform',
    path: '/platform',
    getParentRoute: () => rootRouteImport,
} as any)
const InstitutionsRoute = InstitutionsRouteImport.update({
    id: '/institutions',
    path: '/institutions',
    getParentRoute: () => rootRouteImport,
} as any)
const FinancingRoute = FinancingRouteImport.update({
    id: '/financing',
    path: '/financing',
    getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
    id: '/faq',
    path: '/faq',
    getParentRoute: () => rootRouteImport,
} as any)
const EstatesRoute = EstatesRouteImport.update({
    id: '/estates',
    path: '/estates',
    getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
    '/': typeof IndexRoute
    '/estates': typeof EstatesRoute
    '/faq': typeof FaqRoute
    '/financing': typeof FinancingRoute
    '/institutions': typeof InstitutionsRoute
    '/platform': typeof PlatformRoute
    '/pricing': typeof PricingRoute
    '/tour': typeof TourRoute
}
export interface FileRoutesByTo {
    '/': typeof IndexRoute
    '/estates': typeof EstatesRoute
    '/faq': typeof FaqRoute
    '/financing': typeof FinancingRoute
    '/institutions': typeof InstitutionsRoute
    '/platform': typeof PlatformRoute
    '/pricing': typeof PricingRoute
    '/tour': typeof TourRoute
}
export interface FileRoutesById {
    __root__: typeof rootRouteImport
    '/': typeof IndexRoute
    '/estates': typeof EstatesRoute
    '/faq': typeof FaqRoute
    '/financing': typeof FinancingRoute
    '/institutions': typeof InstitutionsRoute
    '/platform': typeof PlatformRoute
    '/pricing': typeof PricingRoute
    '/tour': typeof TourRoute
}
export interface FileRouteTypes {
    fileRoutesByFullPath: FileRoutesByFullPath
    fullPaths:
        | '/'
        | '/estates'
        | '/faq'
        | '/financing'
        | '/institutions'
        | '/platform'
        | '/pricing'
        | '/tour'
    fileRoutesByTo: FileRoutesByTo
    to:
        | '/'
        | '/estates'
        | '/faq'
        | '/financing'
        | '/institutions'
        | '/platform'
        | '/pricing'
        | '/tour'
    id:
        | '__root__'
        | '/'
        | '/estates'
        | '/faq'
        | '/financing'
        | '/institutions'
        | '/platform'
        | '/pricing'
        | '/tour'
    fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
    IndexRoute: typeof IndexRoute
    EstatesRoute: typeof EstatesRoute
    FaqRoute: typeof FaqRoute
    FinancingRoute: typeof FinancingRoute
    InstitutionsRoute: typeof InstitutionsRoute
    PlatformRoute: typeof PlatformRoute
    PricingRoute: typeof PricingRoute
    TourRoute: typeof TourRoute
}

declare module '@tanstack/react-router' {
    interface FileRoutesByPath {
        '/tour': {
            id: '/tour'
            path: '/tour'
            fullPath: '/tour'
            preLoaderRoute: typeof TourRouteImport
            parentRoute: typeof rootRouteImport
        }
        '/pricing': {
            id: '/pricing'
            path: '/pricing'
            fullPath: '/pricing'
            preLoaderRoute: typeof PricingRouteImport
            parentRoute: typeof rootRouteImport
        }
        '/platform': {
            id: '/platform'
            path: '/platform'
            fullPath: '/platform'
            preLoaderRoute: typeof PlatformRouteImport
            parentRoute: typeof rootRouteImport
        }
        '/institutions': {
            id: '/institutions'
            path: '/institutions'
            fullPath: '/institutions'
            preLoaderRoute: typeof InstitutionsRouteImport
            parentRoute: typeof rootRouteImport
        }
        '/financing': {
            id: '/financing'
            path: '/financing'
            fullPath: '/financing'
            preLoaderRoute: typeof FinancingRouteImport
            parentRoute: typeof rootRouteImport
        }
        '/faq': {
            id: '/faq'
            path: '/faq'
            fullPath: '/faq'
            preLoaderRoute: typeof FaqRouteImport
            parentRoute: typeof rootRouteImport
        }
        '/estates': {
            id: '/estates'
            path: '/estates'
            fullPath: '/estates'
            preLoaderRoute: typeof EstatesRouteImport
            parentRoute: typeof rootRouteImport
        }
        '/': {
            id: '/'
            path: '/'
            fullPath: '/'
            preLoaderRoute: typeof IndexRouteImport
            parentRoute: typeof rootRouteImport
        }
    }
}

const rootRouteChildren: RootRouteChildren = {
    IndexRoute: IndexRoute,
    EstatesRoute: EstatesRoute,
    FaqRoute: FaqRoute,
    FinancingRoute: FinancingRoute,
    InstitutionsRoute: InstitutionsRoute,
    PlatformRoute: PlatformRoute,
    PricingRoute: PricingRoute,
    TourRoute: TourRoute,
}
export const routeTree = rootRouteImport
    ._addFileChildren(rootRouteChildren)
    ._addFileTypes<FileRouteTypes>()
